
services:
  - type: web
    name: crypto-liquidity-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --chdir app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
    autoDeploy: true
